#!/usr/bin/env bash

_sink=53
_timeout=300

down() {
	pamixer --sink "${_sink}" -d 5
	_volume=$(pamixer --sink "${_sink}" --get-volume)
	notify-send -t "${_timeout}" " ${_volume}%"
}

up() {
	pamixer --sink "${_sink}" -i 5
	_volume=$(pamixer --sink "${_sink}" --get-volume)
	notify-send -t "${_timeout}" "  ${_volume}%"
}

mute() {
	_muted="$(pamixer --sink "${_sink}" --get-mute)"
	if ${_muted}; then
		pamixer --sink "${_sink}" -u
		notify-send -t "${_timeout}" " UNMUTED"
	else
		pamixer --sink "${_sink}" -m
		notify-send -t "${_timeout}" " MUTED"
	fi
}

help() {
	_usage="volume 0.0.1 by h4rl

A script for changing volume, custom sink, notification daemon and timeout support,
requires libnotify and pamixer.

usage
volume up: increases volume by 5

volume down: decreases volume by 5

volume mute: mutes the sink

volume: shows this message

"
	echo "${_usage}"
}

case "$1" in
up) up ;;
down) down ;;
mute) mute ;;
*) help ;;
esac
