#!/usr/bin/env bash

sink=53
timeout=300

down() {
	pamixer --sink "${sink}" -d 5
	_volume=$(pamixer --sink "${sink}" --get-volume)
	notify-send -t "${timeout}" " ${volume}%"
}

up() {
	pamixer --sink "${sink}" -i 5
	_volume=$(pamixer --sink "${sink}" --get-volume)
	notify-send -t "${timeout}" "  ${volume}%"
}

mute() {
	_muted="$(pamixer --sink "${sink}" --get-mute)"
	if ${muted}; then
		pamixer --sink "${sink}" -u
		notify-send -t "${timeout}" " UNMUTED"
	else
		pamixer --sink "${sink}" -m
		notify-send -t "${timeout}" " MUTED"
	fi
}

help() {
	_usage="volume 0.0.1 by h4rl

A script for changing volume, custom sink, notification daemon and timeout support,
requires libnotify and pamixer.

usage
volume up: increases volume by 5

volume down: decreases volume by 5

volume mute: mutes the sink

volume: shows this message

"
	echo "${_usage}"
}

case "$1" in
up) up ;;
down) down ;;
mute) mute ;;
*) help ;;
esac
